### ISSUE TITLE
Phase out Glow Squid

### ISSUE THREAD

**Issue by SacredSpirit123** [Derec-Mods/derecearthmod#14]
🎁 **Hide Glow Squids**

📝 Glow Squid won the mob vote at MineCon and are being officially ported over from MCE with the next big expansion, so the modded Glow Squid would be somewhat redundant.

❓ You said something about hiding them as a Debug mob?

**Comment by DereC4** [comment]
Yes, this will happen

**Comment by DereC4** [comment]
I believe it no longer exists lol
