### ISSUE TITLE
Viler Witch

### ISSUE THREAD

**Issue by SacredSpirit123** [Derec-Mods/derecearthmod#18]
🎁 **Viler Witch**

📝 A stronger, more menacing Witch who has mastered the art of potion warfare.

⭐ A Witch who wears more elaborate traditional Witch garb, including a tattered robe and a ratty wide-brimmed hat.

🥟 Viler Witches are stronger than regular Witches, and have learned how to use Lingering Splash Potions along with their regular arsenal. Ever devious, they also enjoy drinking a Potion of Invisibility before attacking their enemies. They are immune to poison and Potions of Harming.

❓ Wiki page [here](https://minecraft.gamepedia.com/Minecraft_Earth:Viler_Witch) , gameplay video [here.](https://youtu.be/yX1upViX-KY)

**Comment by DereC4** [comment]
Will look into this

**Comment by SacredSpirit123** [comment]
Cool. Would be a cool encounter.

**Comment by DereC4** [comment]
It's been added as a miniboss with the latest update!
