### ISSUE TITLE
[Feature Request] Disabling extra dimension in config

### ISSUE THREAD

**Issue by Griefed** [Derec-Mods/derecearthmod#25]
🎁 **Feature Request**

Heya DereC4,
I would love to be able to disable the extra dimension and portal construction in a config-file, if possible. 

📝 Description
Disabling the extra dimension and portal creation with Chest Tappables to prevent entering said dimension.

❓ Anything else you would like to add? Comments? Info?
You're awesome! (Definitely!)
I'm loving Earth Mobs Mod and everything it adds, that includes the extra dimension. However, I want to focus on the three default dimensions of Minecraft for my modpack, therefor it would be awesome if the extra dimension would be an opt-out option. 

Keep up the great work, stay safe and stay awesome.

Cheers,
Griefed

**Comment by DereC4** [comment]
New gamerule does this

**Comment by DereC4** [comment]
Should have something to do with dimensions I forgot the name maybe doearthdimension?

**Comment by Griefed** [comment]
Guessing it is `/toggleexperimental` from looking at the code. That correct?
'Cause I can't find any command like the one you mentioned, or any gamerule related to the dimension. Will test whether that actually disables the dimension. Thanks for your time and for taking this issue up. I really appreciate it. 🙂

Stay safe and stay awesome!
