### ISSUE TITLE
a config option to disable the entire ruby system including the small spring with block on top

### ISSUE THREAD

**Issue by Zygus42** [Derec-Mods/derecearthmod#26]
loving the mobs, but the ruby system and the building are not suitable for my modpack.  Would love a config option to disable these.

**Comment by DereC4** [comment]
Explain what you mean specifically; wasn't there a feature request template? What is conflicting with your modpack? Wdym small spring with a block on top?

**Comment by SacredSpirit123** [comment]
I think they mean the thing you craft/find that lets you use the shop.

**Comment by DereC4** [comment]
ok
