### ISSUE TITLE
[Double Feature Request] - Config for Spawn Control & Option for Wolf Skeleton to Burn in Sun

### ISSUE THREAD

**Issue by Yourname942** [Derec-Mods/derecearthmod#28]
🎁 **Feature Request**

📝 Description
1) A config to configure spawning for each mob
    - min group size
    - max group size
    - spawn weight
    - whitelisted/blacklisted biomes (this where you can prevent them from spawning too)
    example: 
    `	#Add biome types that the Illusioner can spawn in. 
	#Put a "!" before the type to prevent spawning in that biome type. 
	#Leave this blank if you don't want them to spawn at all.
	illusionerBiomeTypes = ["SNOWY", "MOUNTAIN", "!SANDY", "!JUNGLE", "!FOREST", "!HOT", "!MUSHROOM", "!NETHER", "!END"]`
    - whitelisted/blacklisted dimensions
	
2) An option in the config to have skeleton wolves burn up in the sun 
    - for several reasons: 
        a) FATAL ISSUE:
              - they gradually fill up the hostile mob cap as they don't die naturally in the sun, 
                 which prevents any hostile mobs from spawning
        b) some players may want this option, some players may not want the option, but it 
            gives them the choice.

❓ Anything else you would like to add? Comments? Info?
You're awesome!

Minecraft 1.16.4
Forge 35.1.29

**Comment by DereC4** [comment]
For first thing I'm not really good with clothconfig but I'll try; if not i'll definitely lower some mob caps, especially the passive ones albeit only a bit because a point of the mod is to still enrich the world.

**Comment by DereC4** [comment]
I'll try to get this in the next update

It would also help if you suggested some spawn "tiers" (common, uncommon, rare) and which mobs go in which

**Comment by SalehGrey** [comment]
> For first thing I'm not really good with clothconfig but I'll try; if not i'll definitely lower some mob caps, especially the passive ones albeit only a bit because a point of the mod is to still enrich the world.

I would absolutely love to be able to configure which mobs and features are enabled in the mod as well, similar to Quark's config. I think it would be especially useful to modpack developers.

**Comment by DereC4** [comment]
Hey this mod is on haitus as of right now but yeah I'm aware of that and will try

**Comment by DereC4** [comment]
Config progress being made!!

**Comment by DereC4** [comment]
(2.1.3.0) done! (Began working)
