### ISSUE TITLE
Variant pigs won't follow

### ISSUE THREAD

**Issue by Duckster97** [Derec-Mods/derecearthmod#31]
The new pig variants added won't follow me when holding the foods they like (beets, carrots, potatoes). Vanilla pigs follow just fine. 

The variants will get interested, follow briefly, then immediately lose interest, making it impossible to lead them to a farm. I am not sure if this is just a problem im having, do the variants have specific foods they like? I don't see why they would.

Whenever you get the chance would you be able to look into this? No rush, thankfully I have plenty of leads :) awesome mod by the way, love the piggies!

**Comment by DereC4** [comment]
Which specific pig mobs?

**Comment by Duckster97** [comment]
I tried it on the piebald, spotted and... pink footed I think it was.

**Comment by DereC4** [comment]
Ok will take a look when I have time

**Comment by DereC4** [comment]
I see why this is happening and it's being fixed next patch

**Comment by DereC4** [comment]
(2.1.3.0) done!
