### ISSUE TITLE
Mooblooms etc turn fences into flowers

### ISSUE THREAD

**Issue by kvanbiljon** [Derec-Mods/derecearthmod#33]
🐛 **Bug Report**
📝 Description
The various Mooblooms turn my fences into flowers so I can't breed them properly. I'm not sure if this is an issue or something that is meant to be there.

⭐ Describe the solution you'd like
I'd like the fences to not turn into flowers so I can properly breed them. If it's meant to be like that however, I'll figure out a way around it!

🔢 Which version of the mod are you using?
1.16.5

❓ Anything else you would like to add? Comments? Info?
You're awesome!

**Comment by DereC4** [comment]
Send a screenshot of the crime scene (I need to see how your fences are arranged and where they turned into flowers)

**Comment by GregoryDalessandro** [comment]
it is happening to us as well:
Mc 1.16.5
Forge 36.0.39
Earth mobs mod: 2.0.1.3

https://imgur.com/BpDXMSa
https://imgur.com/3rk6jRU
https://imgur.com/F4L9gRr

**Comment by DereC4** [comment]
> It is happening to us as well:
> Mc 1.16.5
> Forge 36.0.39
> Earth mobs mod: 2.0.1.3
> 
> https://imgur.com/BpDXMSa
> https://imgur.com/3rk6jRU
> https://imgur.com/F4L9gRr
> 
> it happened twice in this location for us.
> Are they able to place flowers on any block the fence is on (since the fence is on top of grass)?

Send a screenshot of the crime scene (I need to see how your fences are arranged and where they turned into flowers)

**Comment by SacredSpirit123** [comment]
> > It is happening to us as well:
> > Mc 1.16.5
> > Forge 36.0.39
> > Earth mobs mod: 2.0.1.3
> > https://imgur.com/BpDXMSa
> > https://imgur.com/3rk6jRU
> > https://imgur.com/F4L9gRr
> > it happened twice in this location for us.
> > Are they able to place flowers on any block the fence is on (since the fence is on top of grass)?
> 
> Send a screenshot of the crime scene (I need to see how your fences are arranged and where they turned into flowers)

Did you look at the screenshots from Imgur that they included in the comment? Looks like the mooblooms ripped the fence right out and planted a single flower there.

**Comment by DereC4** [comment]
Yeah idk why I didn't see the images all that time that was an error on my part

**Comment by DereC4** [comment]
Will fix this in next update

**Comment by DereC4** [comment]
Fixed a while ago i think
