### ISSUE TITLE
Certain mobs don't drop cooked meat upon dying on fire

### ISSUE THREAD

**Issue by GoombarioFan** [Derec-Mods/derecearthmod#34]
🐛 **Bug Report**
📝 Description
The following mobs do not dropped their cooked equivalent of meat upon dying due to fire:
Moobloom, Pink Moobloom, Moolip, Midnight Chicken, Stormy Chicken, Amber Chicken, Cluckshroom, Wooly Cow, Horned Sheep

⭐ Describe the solution you'd like
The mobs now drop their cooked equivalent of meat upon death while on fire.

🥟 How to reproduce?
Kill any of the following mobs while they're on fire:
Moobloom, Pink Moobloom, Moolip, Midnight Chicken, Stormy Chicken, Amber Chicken, Cluckshroom, Wooly Cow, Horned Sheep

🔢 Which version of the mod are you using?
2.0.1.3

❓ Anything else you would like to add? Comments? Info?
Muddy Pigs drop cooked porkchops in addition to raw porkchops when dying on fire for some reason. It's the only mob I've observed this with. I figured it was worth mentioning here rather than making another bug report specifically for it.

**Comment by DereC4** [comment]
Alright will work on this when I have time; dont worry

**Comment by DereC4** [comment]
I believe I fixed this with the July update and added more looting compatibility too; could you take a look?

**Comment by DereC4** [comment]
Fixed a while ago
