### ISSUE TITLE
Pale Pig has the wrong name

### ISSUE THREAD

**Issue by GoombarioFan** [Derec-Mods/derecearthmod#35]
🐛 **Bug Report**
📝 Description
The Pale Pig mob is mistakenly named Piebald Pig.

⭐ Describe the solution you'd like
The Pale Pig to be properly called Pale Pig.

🥟 How to reproduce?
When in creative, search for "Piebald Pig Spawn Egg." There should be two results, one being the real Piebald Pig and the other being the Pale Pig. This misnomer can also be observed in Statistics under the Mobs tab.

🔢 Which version of the mod are you using?
1.16-2.0.1.3

❓ Anything else you would like to add? Comments? Info?
You're awesome!

**Comment by DereC4** [comment]
Thanks for your help in reporting this

**Comment by DereC4** [comment]
Being worked on!

**Comment by DereC4** [comment]
(2.1.3.0) done!
