### ISSUE TITLE
server Issues

### ISSUE THREAD

**Issue by sweatyninja15** [Derec-Mods/derecearthmod#38]
🐛 **Bug Report**

When putting this mod into a server mod list it fails to load the server. this issue does not happen when playing a single player world even with all the same mods. Id greatly appreciate any insight/fix to this occurrence, I really enjoy this mod, thanks!

currently using 1.16.5

**Comment by PurpleHel** [comment]
Same problem, tested with only this mod. https://pastebin.com/ZBs3i4Y6

**Comment by DereC4** [comment]
Mod is found to be not server compatible at the moment. This may be worked on in the future; there are too many conflicts I didn't look into when coding this

**Comment by PurpleHel** [comment]
I hope you're able to get it working on servers! I ran into this cos I was trying to set up a home server to take a bit of the strain of playing off my potato of a computer, but I really *like* your mod, and would rather not play without it! Thanks for an awesome mod!
