### ISSUE TITLE
Earth Mobs Mod (v2.1.3.0) Causing Start-Up Crashes on Minecraft 1.16.5 Servers (Forge 36.1.24)

### ISSUE THREAD

**Issue by MarioMario24680** [Derec-Mods/derecearthmod#42]
🐛 **Bug Report**
📝 Description
Whenever you try to load this mod on a Forge server, it will crash the server on start-up.

⭐ Describe the solution you'd like
Prevent the crashes from happening.

🥟 How to reproduce?
Attempt to load the mod on a Forge server.

🔢 Which version of the mod are you using?
I'm using Earth Mobs Mod version 2.1.3.0 for Minecraft 1.16.5 (Forge 36.1.24).

❓ Anything else you would like to add? Comments? Info?
Server-Side Crash Report: 
[crash-2021-06-03_18.01.18-fml.txt](https://github.com/Derec-Mods/derecearthmod/files/6594787/crash-2021-06-03_18.01.18-fml.txt)

A lot of other mods are being loaded at the same time as the Earth Mobs Mod in the crash report shown above, but the stacktrace error thread is still the same even when those mods aren't there to cause any additional problems.

**Comment by DereC4** [comment]
Check the latest version; It attempts to fix a lot of multiplayer bugs. Does it fix some of the crashes?

**Comment by MarioMario24680** [comment]
Yes, thank you very much. Earth Mobs Mod version 2.5.0.0 works without any issues on both singleplayer and multiplayer Minecraft 1.16.5 (I'm trying it now on Forge 36.1.31 instead of Forge 36.1.24, but I think it still works for both).

**Comment by DereC4** [comment]
oh nice
