### ISSUE TITLE
Mud seems to spam its splash sound effect when inside it

### ISSUE THREAD

**Issue by IMadeThisJustToPostThis** [Derec-Mods/derecearthmod#43]
🐛 **Bug Report**
📝 Description
Whenever I go inside of mud, the mud splash sound effect seems to spam creating a very annoying noise. It happened regardless of whether Optifine was installed or not

⭐ Describe the solution you'd like
just fix the sound que 

🥟 How to reproduce?
jump into mud

🔢 Which version of the mod are you using?
2.1.3.0

**Comment by DereC4** [comment]
Thought this was fixed in the next patch but it broke again so I might disable the sound for now
