### ISSUE TITLE
Unregistered ConfiguredFeatures reported by Blame mod

### ISSUE THREAD

**Issue by wasdspace** [Derec-Mods/derecearthmod#44]
🐛 **Bug Report**
📝 Description
Mod's some stuffs are the unregistered ConfiguredFeatures.

⭐ Describe the solution you'd like
Here is the [Blame](https://www.curseforge.com/minecraft/mc-mods/blame) mod's report: 
```
[156月2021 19:02:07.146] [Render thread/ERROR] [com.telepathicgrunt.blame.Blame/]: 

-----------------------------------------------------------------------
****************** Blame Report 1.16.5-3.2.3-forge ******************

 This is an experimental report. It is suppose to automatically read
 the JSON of all the unregistered ConfiguredFeatures, ConfiguredStructures,
 and ConfiguredCarvers. Then does its best to collect the terms that seem to
 state whose mod the unregistered stuff belongs to.

Possible mods responsible for unregistered stuff:

minecraft_earth_mod:jungle_build_plate_ctd
minecraft_earth_mod:jungle_build_plate_lvtd
minecraft_earth_mod:jungle_build_plate_tvtd

-----------------------------------------------------------------------
```
🥟 How to reproduce?
N/A

🔢 Which version of the mod are you using?
2.5.0.0

❓ Anything else you would like to add? Comments? Info?
[latest.log](https://github.com/Derec-Mods/derecearthmod/files/6655247/latest.log)

**Comment by DereC4** [comment]
yeah that's some oudated structure stuff for some reason and then the jungle buildplates are more marshy now because those got removed it shouldnt break the game though
