### ISSUE TITLE
Config to disable mud structure

### ISSUE THREAD

**Issue by IMadeThisJustToPostThis** [Derec-Mods/derecearthmod#45]
🎁 **Feature Request**

📝 Description
I love the mod and honestly think it's configured well from the get go, however I would love a config so we can enable/disable the ruby block-mud structure. It generates too often and is a huge eyesore when combined with generation such as terraforged (it often spawns in mid air)

**Comment by DereC4** [comment]
To be implemented soon

**Comment by DereC4** [comment]
New config option for this in the latest update!
