### ISSUE TITLE
Crash Rendering Pinto Cow forge1.16.5-36.2.4

### ISSUE THREAD

**Issue by velocityraptor-real** [Derec-Mods/derecearthmod#48]
🐛 **Crash Report**
Crash Rendering Pinto Cow
Mod version: 2.5.2.0
Forge version: 1.16.5-36.2.4

[crash-2021-09-19_12.04.34-client.txt](https://github.com/Derec-Mods/derecearthmod/files/7191720/crash-2021-09-19_12.04.34-client.txt)
!

**Comment by DereC4** [comment]
You seem to be using a lot of other mods that could be conflicting; could you try isolating this specific mod and running it and seeing if the crash occurs again?

**Comment by velocityraptor-real** [comment]
Sure thing. will do when I have time again.
I have 2 visual mods namely optifine and obfuscate in the mod that might cause the issue.
I will check if the crash is caused by the base mod or some incompatibility with some other mod

**Comment by DereC4** [comment]
ok thx

**Comment by DereC4** [comment]
Fixed a while ago
