### ISSUE TITLE
More minecraft earth mobs and items

### ISSUE THREAD

**Issue by LionCat3125** [Derec-Mods/derecearthmod#49]
can you add:

-More cows (Wooly Cow,Cookie Cow, Brule Cow, Dairy Cow, Cream Cow,Umbra Cow,and Pinto Cow )

-Rainbow bed

-More pigs (Mottled Pig, Pink Footed Pig,sooty pigs and such)

-Viler Witch (hostile)

-Dyed Cat (peanut butter)

-Rabbit variants (Bold Striped Rabbit,Desert Rabbit,Freckled Rabbit,Harelequin Rabbit,Jumbo Rabbit,Muddy Foot Rabbit,Vested Rabbit)

-the "Mob of me"??

-Sheep variants (Flecked Sheep,Fuzzy Sheep,Inky Sheep,Long Nose Sheep,Patched Sheep,Rocky Sheep)

-Chicken variants (Amber Chicken,Bronzed Chicken,Fancy Chicken,Gold Crested Chicken,Midnight Chicken,Skewbald Chicken,Stormy Chicken

-Zombie Variants (Lobber Zombie,Bouldering Zombie)

**Comment by DereC4** [comment]
Could you split these into more separate issues; very good ideas though

**Comment by DereC4** [comment]
Some of these have already been added, did you check on the main curseforge page and use that as a guide because that's only featuring a few of the things added

**Comment by DereC4** [comment]
Actually most of the things you mentioned have been added such as all the chickens and sheep and the dyed cat, mob of me, all the cows, etc (check the wiki)

**Comment by SacredSpirit123** [comment]
Did you add the Viler Witch yet? I saw her in that list. As well as the mutant zombie variants.

**Comment by DereC4** [comment]
It was added in a patch a few months ago as a miniboss type mob haha

**Comment by DereC4** [comment]
The witch*

**Comment by DereC4** [comment]
Congrats ur in the hall of fame on the wiki now
