### ISSUE TITLE
Cluckshroom bug

### ISSUE THREAD

**Issue by youser123** [Derec-Mods/derecearthmod#61]
🐛 **Bug Report**
📝 Description
Cluckshroom model is broken. Their beaks are seperate from their heads. When you right click them they will convert into normal chickens without using sheers. This means that they can not breed.

🥟 How to reproduce?
Right click cluckshroom.

🔢 Which version of the mod are you using?
Minecraft Earth Mod 2.5.6.1

**Comment by DereC4** [comment]
Was fixed in latest update I believe

**Comment by DereC4** [comment]
It was fixed and ur in the credits now on the wiki page congrats!
