### ISSUE TITLE
Melon Golem bug.

### ISSUE THREAD

**Issue by youser123** [Derec-Mods/derecearthmod#62]
🐛 **Bug Report**
📝 Description
Melon golem is 100% hostile to any mob. They will attack and kill anything in sight.

🥟 How to reproduce?
Make a melon golem.

🔢 Which version of the mod are you using?
Minecraft Earth Mod 2.5.6.1

**Comment by DereC4** [comment]
Was fixed in latest update I believe

**Comment by DereC4** [comment]
It was fixed and ur in the credits now on the wiki page congrats!
