### ISSUE TITLE
Furnace Golem destroying paved roads.

### ISSUE THREAD

**Issue by youser123** [Derec-Mods/derecearthmod#65]
🐛 **Bug Report**
📝 Description
Furnace golems destroy paved roads by walking on them.

🥟 How to reproduce?
Golem walking on paved roads.

🔢 Which version of the mod are you using?
Minecraft Earth Mod 2.5.6.1

**Comment by DereC4** [comment]
To be fixed

**Comment by DereC4** [comment]
It was fixed and ur in the credits now on the wiki page congrats!
