### ISSUE TITLE
Melon Golem heads are comically small

### ISSUE THREAD

**Issue by JoseMV86** [Derec-Mods/derecearthmod#66]
🐛 **Bug Report**
📝 Description
Melon Golem heads are way smaller than their MCEarth's counterpart (https://minecraft.fandom.com/wiki/Minecraft_Earth:Melon_Golem) and, therefore, smaller than a regular Snow Golem's

⭐ Describe the solution you'd like
Making its heads larger

🥟 How to reproduce?
Compare a modded Melon Golem to a MCEarth one

🔢 Which version of the mod are you using?
2.5.8.0

**Comment by DereC4** [comment]
true

**Comment by DereC4** [comment]
UM i can't model this at the moment because i am in university now but ty for being one of the first bug reporters
