### ISSUE TITLE
Mob Texture Issue

### ISSUE THREAD

**Issue by GodBerrie** [Derec-Mods/derecearthmod#67]
🐛 **Bug Report**
📝 Description
Most mobs from the mod seem to have a broken model that makes them look like a player model with a broken texture. The only exception ive seen so far is the muddy pig.

**Comment by DereC4** [comment]
oh jeez is this for 1.17

**Comment by GodBerrie** [comment]
> 

It is, yeah. A little spooky to see a man walking around with a cow texture.

**Comment by DereC4** [comment]
Fixed a while ago
