### ISSUE TITLE
1.18?

### ISSUE THREAD

**Issue by AndyKitty8** [Derec-Mods/derecearthmod#69]
Hiya, just wondering if there’s a 1.18 version in the works and if you have a time estimate for its release :)

Sorry if this posted twice, I thought it posted the first time but when I went back it was gone.

**Comment by AndyKitty8** [comment]
Ok yeah it did post twice, please ignore the first one😅

**Comment by DereC4** [comment]
In the works don't worry

**Comment by DereC4** [comment]
Sorry for the wait; 1.19 is out now! Lemme know in the issue tracker if there are any missing features
