### ISSUE TITLE
mobs look like a buggy human

### ISSUE THREAD

**Issue by hihihihihqq** [Derec-Mods/derecearthmod#71]
🐛 **Bug Report**
A bunch of mobs like wooly cow, all the sheeps, gold crested chicken

Make them not look like a human

1.19.2

**Comment by DereC4** [comment]
Are you sure you're using the correct 1.19 version? The latest one I spent an entire day making sure the models were converted into the 1.19 formats from the 1.16.5 formats

**Comment by DereC4** [comment]
Also could you show me any screenshots of the behavior you're observing

**Comment by Devaraja99** [comment]
I'm also having this issue with version 5.1.1.0 of the mod and Forge 43.2.4 and 43.2.0. The tropical slime, glowing squid test, all of the sheep, and the wooly cow appear as bugged humans, but I haven't seen any issue with the gold crested chicken. This occurs with no other mods present.
Here's a screenshot of the affected mobs, plus the gold crested chicken:
![2023-02-04_07 17 08](https://user-images.githubusercontent.com/105709066/216767266-3efb8eae-f0c8-4615-8c54-470a35ab01bb.png)

**Comment by DereC4** [comment]
Ah I'll take a look at all those entities then

**Comment by DereC4** [comment]
Fixed in 5.1.2.0!!! Thanks for your help; added you to the hall of fame
