### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by FanRenLa** [Derec-Mods/derecearthmod#72]
🐛 **Bug Report**
📝 Description
I didn't do anything. The game crashed.

⭐ Describe the solution you'd like
Solve the crash.

🥟 How to reproduce?
Put a pig into mud

🔢 Which version of the mod are you using?
MinecraftEarthMod-5.1.0.0

❓ Anything else you would like to add? Comments? Info?
You're awesome!
[crash-2023-01-08_15.01.03-client.txt](https://github.com/Derec-Mods/derecearthmod/files/10367870/crash-2023-01-08_15.01.03-client.txt)
[latest.log](https://github.com/Derec-Mods/derecearthmod/files/10367871/latest.log)

**Comment by FanRenLa** [comment]
I don't know if the author can optimize the mod, to be honest it's a little bit more crappy than other mods.
I often crash because of this mod.

**Comment by DereC4** [comment]
> I don't know if the author can optimize the mod, to be honest it's a little bit more crappy than other mods. I often crash because of this mod.

Oh the 1.19 version is fairly new and untested because a lot of people were asking for a port so it's up to people like you to help me report the things I missed when testing.
Thanks for the issue btw hopefully i can figure it out soon

**Comment by FanRenLa** [comment]
I see. I understand. I like your mod very much, but want better game performance.

**Comment by DereC4** [comment]
No worries; honestly I'd love it if people could just come up and report every single problem they had with the mod because I alone can't test them all 😭

**Comment by FanRenLa** [comment]
![QQ截图20230112144100](https://user-images.githubusercontent.com/83486178/211996080-e2a19d8d-077c-470a-b316-de4da7a7edfc.png)
![QQ截图20230112144038](https://user-images.githubusercontent.com/83486178/211996104-c7d3e099-4b14-4efb-bcdc-780a09480319.png)
