### ISSUE TITLE
[1.19.2-5.1.1.0] Oversized textures from Earth Mobs Mod in texture atlas

### ISSUE THREAD

**Issue by TelepathicGrunt** [Derec-Mods/derecearthmod#74]
I was texting out the Atlas Viewer mod ( https://www.curseforge.com/minecraft/mc-mods/atlasviewer ) and discovered that Earth Mobs Mod has several way too oversized textures taking up too much memory and space in the block/item texture atlas

![image](https://user-images.githubusercontent.com/40846040/213591196-cd6e301e-5368-4a67-92ad-3fa09e38e8a3.png)
![image](https://user-images.githubusercontent.com/40846040/213591204-5f43c0e3-e5b6-48c8-82d2-a5b2171d0864.png)

The following textures should be significantly reduced in resolution to match mc's 16x16 textures to ease up on memory usage/atlas bloating:

- minecraft_earth_mod:blocks/missingtexture
- minecraft_earth_mod:items/missingtexture
- minecraft_earth_mod:blocks/stonetappablesides
- minecraft_earth_mod:blocks/stonetappabletop
- minecraft_earth_mod:items/bone_shard
- minecraft_earth_mod:items/horn

**Comment by DereC4** [comment]
This is a great issue; thanks for reminding me. A lot of those textures were put together and thrown in the files back when the mod was messier and more unorganized and were never attended to. Will be fixing these textures in the upcoming update. 
Keep up the good work!

**Comment by DereC4** [comment]
Fixed in 5.1.2.0, thanks!
