### ISSUE TITLE
Wooly cow + horned sheep model bug

### ISSUE THREAD

**Issue by Milanovsk1** [Derec-Mods/derecearthmod#76]
🐛 **Bug Report**
📝 Description
- Wooly cows and horned sheep have a player-like model

⭐ Describe the solution you'd like
- Give them their correct model :)

🥟 How to reproduce?
- Use their spawn egg or find them in the wild

🔢 Which version of the mod are you using?
- Mod version: 1.19.2 - 5.1.2.0
- Minecraft version: 1.19.2
- Forge version: 43.2.0
<img width="1440" alt="Screenshot 2023-02-18 at 18 39 56" src="https://user-images.githubusercontent.com/118830064/219880945-2c481a1a-4a06-4803-af5d-5711471c57fd.png">
<img width="1440" alt="Screenshot 2023-02-18 at 18 40 08" src="https://user-images.githubusercontent.com/118830064/219880953-ebebadb9-c6b2-4b95-bafa-cb1a852ef956.png">

❓ Anything else you would like to add? Comments? Info?
- Very nice mod!

**Comment by DereC4** [comment]
Oh dear I'll get to this right away

**Comment by DereC4** [comment]
Fixed in 5.1.3.0
