### ISSUE TITLE
Rocky sheep + bouldering zombie model bug

### ISSUE THREAD

**Issue by Milanovsk1** [Derec-Mods/derecearthmod#77]
🐛 Bug Report
📝 Description
Rocky sheep and bouldering zombie have a broken models

⭐ Describe the solution you'd like
Give them their correct model :)

🥟 How to reproduce?
Use their spawn egg 

🔢 Which version of the mod are you using?
Mod version: 1.19.2 - 5.1.3.0
Minecraft version: 1.19.2
Forge version: 43.2.0

<img width="1440" alt="Screenshot 2023-02-20 at 01 00 06" src="https://user-images.githubusercontent.com/118830064/220186956-a5d7e01e-2ae0-4925-9fe5-d0184b8c8479.png">
<img width="1440" alt="Screenshot 2023-02-20 at 01 00 08" src="https://user-images.githubusercontent.com/118830064/220186972-8682e829-5f77-46f7-af98-b5cca0d04416.png">

❓ Anything else you would like to add? Comments? Info?
You're awesome!

**Comment by DereC4** [comment]
Bouldering Zombie is a work in progress that I'm working on with custom animations and models! (Coming soon!) So don't wrry about that it doesn't spawn naturally yet.

Rocky sheep I'll get to right away, thanks for reporting!

**Comment by DereC4** [comment]
Fixed a month ago or so oopsies
