### ISSUE TITLE
Melon Golem Bug

### ISSUE THREAD

**Issue by seijitsuni** [Derec-Mods/derecearthmod#78]
🐛 **Bug Report**
📝 Description
Melon Golems have crooked model. 

⭐ Describe the solution you'd like
Check if melon golems spawn with the right model and not a humanoid Model.

🥟 How to reproduce?
Any Melon Golem spawn probably, maybe shader related.

🔢 Which version of the mod are you using?
1.19.2 5.2.1.0

![Melon golem](https://user-images.githubusercontent.com/130250347/230740702-6103b7d9-35d0-45ef-9f6c-cceb7bd4ca35.jpg)

**Comment by DereC4** [comment]
Going to be fixed in the latest version, thanks for reporting! Must have missed a model while porting to 1.19

**Comment by DereC4** [comment]
Should be fixed in the latest update along with a few melon golem buffs! Thanks
