### ISSUE TITLE
Confusion with Minecraft Version

### ISSUE THREAD

**Issue by PsydameousSharm** [Derec-Mods/derecearthmod#79]
🐛 **Bug Report**
📝 Description
On Curseforge, it says your most recent file is 1.19.4, but when I try to load it up, says it's for 1.19.2

⭐ Describe the solution you'd like
Update it for 1.19.4

🥟 How to reproduce?
Open Curseforge, and install your mod on 1.19.4 profile, and load it up.

🔢 Which version of the mod are you using?
5.2.1.0

❓ Anything else you would like to add? Comments? Info?
You're awesome!
This is an amazing mod, and I would love to use it on my server, good work!

**Comment by DereC4** [comment]
I forgot to mark this 1 year ago as fixed oops
