### ISSUE TITLE
Mod being reported as 1.19.4 but is only 1.19.2

### ISSUE THREAD

**Issue by kreezxil** [Derec-Mods/derecearthmod#80]
🐛 **Bug Report**
📝 Description
[1.19.2-5.2.3.0](https://www.curseforge.com/minecraft/mc-mods/minecraft-earth-mod/files/4481746)

⭐ Describe the solution you'd like
Fix the tag so that cflauncher doesn't allow me to put your mod in my 1.19.4 pack. or update it to work on 1.19.4 either way works for me.

🥟 How to reproduce?
Build a pack using cflauncher, start it as forge 1.19.4, add new mods via the mod browser, search for earth, add earth mods that way. Be amazed as a mod that demands 1.19.2 is added to your 1.19.4 packs.

🔢 Which version of the mod are you using?
1.19.2-5.2.3.0

❓ Anything else you would like to add? Comments? Info?
Here's a crash report: https://paste.centos.org/view/381211c3

**Comment by DereC4** [comment]
*be amazed* 😭

I think the version you linked has 1.19.2 as the highest version though, am a bit confused. But yeah the mod **should** be for 1.19.2 for now before I port it to 1.19.4 im not sure why it's registering it as such on your mod loader.

**Comment by DereC4** [comment]
Oops forgot to mark this as fixed 1 year ago
