### ISSUE TITLE
Will you be making a Fabric port?

### ISSUE THREAD

**Issue by allanonmage** [Derec-Mods/derecearthmod#86]
🎁 **Feature Request**

📝 Description
Port to Fabric

⭐ Describe what the mob is like
It's like Forge, but different.

🥟 Any special features it has from Minecraft Earth?
It loads different mods.

❓ Anything else you would like to add? Comments? Info?
You're awesome! I would like this on my Fabric server.

**Comment by DereC4** [comment]
Sadly fabric uses an entirely different API and im in university now (i started this mod back in early high school) so I can not make the port

**Comment by DereC4** [comment]
;-;
