### ISSUE TITLE
Aternos server problem

### ISSUE THREAD

**Issue by FenrirOdin** [Derec-Mods/derecearthmod#89]
Hello i have a problem with the mod
after many attempts my server crashes
Im trying to delete the mod from the server
But after removing it from the files in aternos it crashes saying its missing and i dont know what to delete

https://mclo.gs/3js9Ymr

**Comment by DereC4** [comment]
Hey! Thanks for your bug report. I'm gonna need more details so I sadly have to close your issue and ask you to make it again with the proper template, because the template guides you through what additional information is needed.
