### ISSUE TITLE
LobberZombie 1.20.1

### ISSUE THREAD

**Issue by Ymadbroitme** [Derec-Mods/derecearthmod#93]
so I am playing a modpack in 1.20.1 and I decided to load the "Lobber Zombie" mod, However I get this message
 "The game crashed whilst rendering overlay
Error: software.bernie.geckolib.GeckoLibException: minecraft_earth_mod:animations/lobberzombie.animation.json: Error loading animation file"

**Comment by Ymadbroitme** [comment]
I had to edit it

**Comment by DereC4** [comment]
oop im busy with [Longhorn Developers](https://github.com/Longhorn-Developers) rn but i will get back to u for sure, might just disable the zombies if they didnt translate well to the newer versions
